### ISSUE TITLE
HF - App crashes when a user tries to access medical history(Child register - child profile) - NullpointerException

### ISSUE THREAD

**Issue by Mstjamush** [OpenSRP/opensrp-client-chw#1703]
App crashes when a user tries to access medical history(Child register - child profile) - NullpointerException
```
02-15 14:12:34.396  5241  5409 D ClientProcessorForJava: Starting updateFTSsearch table: ec_family_member
02-15 14:12:34.421  5241  5443 E AndroidRuntime: FATAL EXCEPTION: pool-33-thread-1
02-15 14:12:34.421  5241  5443 E AndroidRuntime: Process: org.smartregister.chw.hf, PID: 5241
02-15 14:12:34.421  5241  5443 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'java.util.List org.smartregister.immunization.util.VaccineCache.vaccineRepo' on a null object reference
02-15 14:12:34.421  5241  5443 E AndroidRuntime: 	at org.smartregister.chw.core.utils.VisitVaccineUtil.getAllVaccines(VisitVaccineUtil.java:56)
02-15 14:12:34.421  5241  5443 E AndroidRuntime: 	at org.smartregister.chw.core.interactor.CoreChildMedicalHistoryActivityInteractor.getVaccinesReceivedGroup(CoreChildMedicalHistoryActivityInteractor.java:85)
02-15 14:12:34.421  5241  5443 E AndroidRuntime: 	at org.smartregister.chw.core.interactor.CoreChildMedicalHistoryActivityInteractor.lambda$getMemberHistory$1$CoreChildMedicalHistoryActivityInteractor(CoreChildMedicalHistoryActivityInteractor.java:35)
02-15 14:12:34.421  5241  5443 E AndroidRuntime: 	at org.smartregister.chw.core.interactor.-$$Lambda$CoreChildMedicalHistoryActivityInteractor$C9p5nKqT_P3cR_HzXtAz0IowsF4.run(Unknown Source:6)
02-15 14:12:34.421  5241  5443 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
02-15 14:12:34.421  5241  5443 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
02-15 14:12:34.421  5241  5443 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
02-15 14:12:34.425  3643  4330 D Debug   : !@DumpState : SHIP
```

**Comment by Mstjamush** [comment]
Fixed
