### ISSUE TITLE
HF -  App crashes when a user tries to "View house location" from a ANC profile

### ISSUE THREAD

**Issue by Mstjamush** [OpenSRP/opensrp-client-chw#1704]
App crashes when a user tries to "View house location" from a ANC profile
```

02-15 14:03:12.037  3413  3413 D AndroidRuntime: Shutting down VM
02-15 14:03:12.039  3413  3413 E AndroidRuntime: FATAL EXCEPTION: main
02-15 14:03:12.039  3413  3413 E AndroidRuntime: Process: org.smartregister.chw.hf, PID: 3413
02-15 14:03:12.039  3413  3413 E AndroidRuntime: android.content.ActivityNotFoundException: Unable to find explicit activity class {org.smartregister.chw.hf/org.smartregister.chw.core.activity.CoreAncMemberMapActivity}; have you declared this activity in your AndroidManifest.xml?
02-15 14:03:12.039  3413  3413 E AndroidRuntime: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1950)
02-15 14:03:12.039  3413  3413 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1622)
02-15 14:03:12.039  3413  3413 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4564)
02-15 14:03:12.039  3413  3413 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
02-15 14:03:12.039  3413  3413 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4522)
02-15 14:03:12.039  3413  3413 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:662)
02-15 14:03:12.039  3413  3413 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:4883)
02-15 14:03:12.039  3413  3413 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:4851)
02-15 14:03:12.039  3413  3413 E AndroidRuntime: 	at org.smartregister.chw.core.activity.CoreAncMemberProfileActivity.openFamilyLocation(CoreAncMemberProfileActivity.java:276)
02-15 14:03:12.039  3413  3413 E AndroidRuntime: 	at org.smartregister.chw.anc.activity.BaseAncMemberProfileActivity.onClick(BaseAncMemberProfileActivity.java:495)
02-15 14:03:12.039  3413  3413 E AndroidRuntime: 	at org.smartregister.chw.core.activity.CoreAncMemberProfileActivity.onClick(CoreAncMemberProfileActivity.java:160)
02-15 14:03:12.039  3413  3413 E AndroidRuntime: 	at android.view.View.performClick(View.java:6897)
02-15 14:03:12.039  3413  3413 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:26101)
02-15 14:03:12.039  3413  3413 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
02-15 14:03:12.039  3413  3413 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
02-15 14:03:12.039  3413  3413 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
02-15 14:03:12.039  3413  3413 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6944)
02-15 14:03:12.039  3413  3413 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-15 14:03:12.039  3413  3413 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
02-15 14:03:12.039  3413  3413 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
02-15 14:03:12.044  3413  3557 I CommonRepository: Fts Row Updated: 1
02-15 14:03:12.045  3413  3557 I CommonRepository: Fts Row Updated: 1
02-15 14:03:12.046  3643 10594 D Debug   : !@DumpState : SHIP
```

**Comment by Mstjamush** [comment]
Fixed
