### ISSUE TITLE
Boresha Afya Fixes: App crashes when a user clicks on a ANC profile's View house location

### ISSUE THREAD

**Issue by samkanga** [opensrp/opensrp-client-chw#2079]
APK - Kituoni (HF)
Android 7

When one clicks on an ANC Profile to View House Location the App crashes. See the following logs.
```
07-04 16:06:16.147  1259  6724 I ActivityTaskManager: START u0 {cmp=org.smartregister.chw.hf/org.smartregister.chw.core.activity.CoreAncMemberMapActivity (has extras)} from uid 10337
		07-04 16:06:16.148 30551 30551 D AndroidRuntime: Shutting down VM
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: FATAL EXCEPTION: main
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: Process: org.smartregister.chw.hf, PID: 30551
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: android.content.ActivityNotFoundException: Unable to find explicit activity class {org.smartregister.chw.hf/org.smartregister.chw.core.activity.CoreAncMemberMapActivity}; have you declared this activity in your AndroidManifest.xml?
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2078)
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1727)
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:5377)
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:5335)
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:662)
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:5721)
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:5674)
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: 	at org.smartregister.chw.core.activity.CoreAncMemberProfileActivity.openFamilyLocation(CoreAncMemberProfileActivity.java:276)
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: 	at org.smartregister.chw.anc.activity.BaseAncMemberProfileActivity.onClick(BaseAncMemberProfileActivity.java:495)
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: 	at org.smartregister.chw.core.activity.CoreAncMemberProfileActivity.onClick(CoreAncMemberProfileActivity.java:160)
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: 	at android.view.View.performClick(View.java:8160)
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:8137)
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: 	at android.view.View.access$3700(View.java:888)
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:30236)
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:246)
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8653)
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
		07-04 16:06:16.151 30551 30551 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
		07-04 16:06:16.156  1259  7733 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
		07-04 16:06:16.156  5257  5330 D NetworkController.SecMobileSignalController(1/1): onSignalStrengthsChanged level=4
		07-04 16:06:16.157  1259  6724 D Debug   : low && ship && 3rd party app crash, so skip dump

```

**Comment by samkanga** [comment]
@hilpitome @ekigamba what Mapbox key should we use for the BA App?

**Comment by ekigamba** [comment]
@samkanga 
Has this app been in production? Give me some more details so that I can figure out which is the right Mapbox key because Mapbox has billing associated with it. Alternatively, we can ask Megan or check the Bitwarden collection

**Comment by samkanga** [comment]
@ekigamba yes, it has been in production but not in active use. The client is planning a relaunch of the App hence the ongoing QA and fixes.

**Comment by ekigamba** [comment]
@samkanga I have shared the API Key

**Comment by faith-mutua** [comment]
@samkanga this issue has now been resolved
